# Generated by Django 4.2.27 on 2026-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pizza_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProveedor', models.CharField(max_length=30)),
                ('emailProveedor', models.EmailField(max_length=100, unique=True)),
                ('telefonoProveedor', models.CharField(blank=True, max_length=11)),
                ('fechaAlta', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
